/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.43 from the
 * contents of perltoc.xs. Do not edit this file, edit perltoc.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
#define PERL_NO_GET_CONTEXT
#define PERL_EUPXS_ALWAYS_EXPORT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#define PCRE2_CODE_UNIT_WIDTH 8
#define PCRE2_STATIC

#include "./main.h"

#line 21 "/Users/sasho/cllvmbackendlocal/perltoc.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 165 "/Users/sasho/cllvmbackendlocal/perltoc.c"

XS_EUPXS(XS__startmatching); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS__startmatching)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "in, in1, in2, in3");
    {
#line 18 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    STRLEN len;
    STRLEN secondlen;
    STRLEN thirdlen;
    STRLEN fourthlen;
    char* s;
    char* s1;
    char* s2;
    char* s3;
#line 183 "/Users/sasho/cllvmbackendlocal/perltoc.c"
	extern	RETVAL;
	SV *	in = ST(0)
;
	SV *	in1 = ST(1)
;
	SV *	in2 = ST(2)
;
	SV *	in3 = ST(3)
;
#line 27 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    {
        int secondmain(char *subject, size_t szsubject, char *pattern, size_t szpattern, char *modulename, size_t szmodulename,
            char*, size_t);
        s = SvPVutf8(in, len);
        s1 = SvPVutf8(in1, secondlen);
        s2 = SvPVutf8(in2, thirdlen);
        s3 = SvPVutf8(in3, fourthlen);
        secondmain(s, len, s1, secondlen, s2, thirdlen, s3, fourthlen);
    }
#line 203 "/Users/sasho/cllvmbackendlocal/perltoc.c"
    }
    XSRETURN(1);
}


XS_EUPXS(XS__callout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS__callout)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "in, hash, pos");
    {
	U32	RETVAL;
	dXSTARG;
	SV *	in = ST(0)
;
	HV *	hash;
	U32	pos = (unsigned long)SvUV(ST(2))
;

	STMT_START {
		SV* const xsub_tmp_sv = ST(1);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVHV){
		    hash = (HV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not a HASH reference",
				"callout",
				"hash");
		}
	} STMT_END
;
#line 59 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    {
        extern U32 do_callout(SV* in, HV* hash, U32 pos);

        RETVAL = do_callout(in, hash, pos);
    }
#line 243 "/Users/sasho/cllvmbackendlocal/perltoc.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS__initthread1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS__initthread1)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "baseposarg");
    {
	U32	baseposarg = (unsigned long)SvUV(ST(0))
;
#line 71 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    {
        extern __thread U32 matchpos, basepos;
        //printf("print digit %d\n", baseposarg);
	    basepos = baseposarg;
	    initthread();
    }
#line 266 "/Users/sasho/cllvmbackendlocal/perltoc.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS__consumefilescopes1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS__consumefilescopes1)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "id");
    {
	U32	id = (unsigned long)SvUV(ST(0))
;
#line 81 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    {
        //extern __thread U32 matchpos, basepos;
        //printf("print digit %d\n", baseposarg);
	    //basepos = baseposarg;
	    consumefilescopes(id);
    }
#line 288 "/Users/sasho/cllvmbackendlocal/perltoc.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS__registerthread1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS__registerthread1)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "id");
    {
	U32	id = (unsigned long)SvUV(ST(0))
;
#line 91 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    {
        //extern __thread U32 matchpos, basepos;
        //printf("print digit %d\n", baseposarg);
	    //basepos = baseposarg;
	    //registerthread(id);
    }
#line 310 "/Users/sasho/cllvmbackendlocal/perltoc.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS__broadcast1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS__broadcast1)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "thrid, currid");
    {
	U32	thrid = (unsigned long)SvUV(ST(0))
;
	U32	currid = (unsigned long)SvUV(ST(1))
;
#line 101 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    {
        //extern __thread U32 matchpos, basepos;
        //printf("print digit %d\n", baseposarg);
	    //basepos = baseposarg;
	    broadcast(thrid, currid);
    }
#line 334 "/Users/sasho/cllvmbackendlocal/perltoc.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS__flushfilescopes1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS__flushfilescopes1)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "maxthreads, id");
    {
	U32	maxthreads = (unsigned long)SvUV(ST(0))
;
	U32	id = (unsigned long)SvUV(ST(1))
;
#line 111 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    {
        //extern __thread U32 matchpos, basepos;
        //printf("print digit %d\n", baseposarg);
	    //basepos = baseposarg;
	    flushfilescopes(maxthreads, id);
    }
#line 358 "/Users/sasho/cllvmbackendlocal/perltoc.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS__startmodule); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS__startmodule)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "in");
    {
#line 130 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    STRLEN len;
    char* s;
#line 374 "/Users/sasho/cllvmbackendlocal/perltoc.c"
	extern	RETVAL;
	SV *	in = ST(0)
;
#line 133 "/Users/sasho/cllvmbackendlocal/perltoc.xs"
    {
        void startmodule(const char* modulename, size_t szmodulename);
        s = SvPVutf8(in, len);

        startmodule(s, len);
    }
#line 385 "/Users/sasho/cllvmbackendlocal/perltoc.c"
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_AnFunctionArray); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_AnFunctionArray)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        (void)newXSproto_portable("startmatching", XS__startmatching, file, "$$$$");
        (void)newXSproto_portable("callout", XS__callout, file, "$$$");
        (void)newXSproto_portable("initthread1", XS__initthread1, file, "$");
        (void)newXSproto_portable("consumefilescopes1", XS__consumefilescopes1, file, "$");
        (void)newXSproto_portable("registerthread1", XS__registerthread1, file, "$");
        (void)newXSproto_portable("broadcast1", XS__broadcast1, file, "$$");
        (void)newXSproto_portable("flushfilescopes1", XS__flushfilescopes1, file, "$$");
        (void)newXSproto_portable("startmodule", XS__startmodule, file, "$");
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

